#!/usr/bin/env python3
"""
FOURTH & CENTRAL COMMUNITY WATCH (FCCW) - CIVIC WATCHDOG ENGINE
Author: Generated by Gemini Notebook for FCCW Open-Source Initiative
License: Open Source (GPL-3.0)
Year: 2026

This production-grade script implements a comprehensive civic watchdog system for
monitoring, auditing, and mitigating speculative displacement and misinformation
surrounding the $2B Fourth & Central development in Skid Row.

Modules Included:
  1. TRACK A: GIS Zoning Audit Engine (Spatial containment & lux incursion detector)
  2. TRACK B: SRO 1:1 Replacement Ledger (Relational audit matching lost vs covenanted units)
  3. TRACK C: Prosocial Civic Trust Portal (Countering SoM - Sense of Misinformation via NLP)
"""

import sqlite3
import re
from dataclasses import dataclass


@dataclass(frozen=True)
class ProjectAudit:
    status: str
    reason: str


def audit_project(
    latitude: float,
    longitude: float,
    affordable_percent: float,
) -> ProjectAudit:
    """Classify a project against the monitored Skid Row thresholds."""
    bounds = ZoningAuditEngine.SKID_ROW_BOUNDS
    inside = (
        bounds["lat_south"] <= latitude <= bounds["lat_north"]
        and bounds["lon_west"] <= longitude <= bounds["lon_east"]
    )
    if inside and affordable_percent < 80:
        return ProjectAudit(
            "CRITICAL VIOLATION",
            "Inside IX1 boundary below 80% affordability",
        )
    if affordable_percent < 15:
        return ProjectAudit(
            "BUFFER WATCH",
            "Below 15% affordability near the monitored boundary",
        )
    if inside:
        return ProjectAudit(
            "PASS",
            "Inside monitored boundary and meets the 80% threshold",
        )
    return ProjectAudit("OUTSIDE SCOPE", "Project is outside the monitored boundary")


def replacement_ledger_status(units_lost: int, covenanted_units: int) -> ProjectAudit:
    """Check the SRO one-for-one replacement requirement."""
    if units_lost < 0 or covenanted_units < 0:
        raise ValueError("Unit counts cannot be negative")
    if covenanted_units < units_lost:
        return ProjectAudit(
            "CRITICAL VIOLATION",
            "Replacement units do not meet the 1:1 requirement",
        )
    return ProjectAudit(
        "PASS",
        "Replacement units meet or exceed the 1:1 requirement",
    )

# ==============================================================================
# COLORFUL TERMINAL CONFIGURATION
# ==============================================================================
class TerminalColors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

# ==============================================================================
# TRACK A: GIS ZONING AUDIT ENGINE (SPATIAL AUDITOR)
# ==============================================================================
class ZoningAuditEngine:
    """
    Simulates a Geographic Information System (GIS) coordinate auditor.
    Skid Row boundaries are established as:
      - North: 3rd Street (lat: 34.0482)
      - South: 7th Street (lat: 34.0410)
      - West: Main Street (lon: -118.2495)
      - East: Alameda Avenue (lon: -118.2360)
    """
    SKID_ROW_BOUNDS = {
        'lat_north': 34.0482,
        'lat_south': 34.0410,
        'lon_west': -118.2495,
        'lon_east': -118.2360
    }

    @classmethod
    def is_within_skid_row(cls, lat, lon):
        within_lat = cls.SKID_ROW_BOUNDS['lat_south'] <= lat <= cls.SKID_ROW_BOUNDS['lat_north']
        within_lon = cls.SKID_ROW_BOUNDS['lon_west'] <= lon <= cls.SKID_ROW_BOUNDS['lon_east']
        return within_lat and within_lon

    @classmethod
    def audit_development_proposal(cls, project_name, lat, lon, proposed_units, affordable_units, zoning_requested):
        """
        Evaluates proposed zoning against Skid Row's protective IX1 (Affordable Housing Only) boundary.
        """
        is_in_skid_row = cls.is_within_skid_row(lat, lon)
        affordability_ratio = (affordable_units / proposed_units) if proposed_units > 0 else 0
        
        status = {
            "project": project_name,
            "coordinates": (lat, lon),
            "inside_skid_row": is_in_skid_row,
            "affordability_rate": round(affordability_ratio * 100, 2),
            "zoning_compliance": "PASS",
            "warnings": [],
            "severity": "INFO"
        }

        if is_in_skid_row:
            # IX1 Zone demands maximum affordable protection (Inclusionary mandates)
            if zoning_requested in ["IX1", "IX2", "IX4"] or zoning_requested.startswith("R"):
                if affordability_ratio < 0.80 and zoning_requested == "IX1":
                    status["zoning_compliance"] = "CRITICAL VIOLATION"
                    status["warnings"].append("IX1 Zone requires minimum 80% covenanted low-income housing!")
                    status["severity"] = "CRITICAL"
                elif affordability_ratio < 0.20:
                    status["zoning_compliance"] = "WARNING"
                    status["warnings"].append("Low affordability rate inside Skid Row boundaries is a gentrification trigger.")
                    status["severity"] = "WARNING"
                    
            if zoning_requested in ["IX2", "IX4"] and proposed_units > 500:
                status["warnings"].append("Excessive square footage/density in commercial buffers; adaptive reuse caps might be exceeded.")
                if status["severity"] != "CRITICAL":
                    status["severity"] = "WARNING"
        else:
            # Project is outside Skid Row, but check if it's on the boundary (Buffer Zone check)
            # A projects within 0.005 degrees of Skid Row bounds is considered on the "Strong Edge" buffer
            buffer_dist = 0.005
            is_near_boundary = (
                abs(lat - cls.SKID_ROW_BOUNDS['lat_north']) < buffer_dist or
                abs(lat - cls.SKID_ROW_BOUNDS['lat_south']) < buffer_dist or
                abs(lon - cls.SKID_ROW_BOUNDS['lon_west']) < buffer_dist or
                abs(lon - cls.SKID_ROW_BOUNDS['lon_east']) < buffer_dist
            )
            if is_near_boundary and affordability_ratio < 0.15:
                status["zoning_compliance"] = "BUFFER INVASION"
                status["warnings"].append("Speculative pressure alert! Luxury build on Skid Row perimeter threatens buffer stability.")
                status["severity"] = "WARNING"

        return status

# ==============================================================================
# TRACK B: SRO 1:1 REPLACEMENT LEDGER (DATABASE ENGINE)
# ==============================================================================
class SROLedgerEngine:
    """
    Manages a relational database tracing SRO unit inventories and auditing
    redevelopment permits against active 1:1 replacement covenants.
    """
    def __init__(self, db_path=":memory:"):
        self.conn = sqlite3.connect(db_path)
        self.conn.row_factory = sqlite3.Row
        self._initialize_database()

    def _initialize_database(self):
        cursor = self.conn.cursor()
        # Enable Foreign Keys
        cursor.execute("PRAGMA foreign_keys = ON;")
        
        # SRO Hotel registry
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS sro_hotels (
                id TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                street_address TEXT NOT NULL,
                total_historic_units INTEGER NOT NULL,
                current_active_units INTEGER NOT NULL,
                operator_nonprofit TEXT
            );
        """)
        
        # Replacement Covenants Track
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS replacement_covenants (
                id TEXT PRIMARY KEY,
                redevelopment_project TEXT NOT NULL,
                original_hotel_id TEXT REFERENCES sro_hotels(id),
                units_demolished INTEGER NOT NULL,
                replacement_units_covenanted INTEGER NOT NULL,
                replacement_site_address TEXT NOT NULL,
                covenant_status TEXT CHECK(covenant_status IN ('Pending', 'Certified', 'Violated')),
                recorded_date TEXT DEFAULT CURRENT_TIMESTAMP
            );
        """)
        self.conn.commit()

    def seed_initial_sro_data(self):
        cursor = self.conn.cursor()
        sro_data = [
            ("renato-01", "Renato Apartments SRO", "538 S San Julian St", 100, 100, "SRO Housing Corp"),
            ("baltimore-02", "Baltimore Hotel", "501 S Los Angeles St", 150, 150, "AIDS Healthcare Foundation"),
            ("king-edward-03", "King Edward Hotel", "121 E 5th St", 120, 120, "AIDS Healthcare Foundation"),
            ("madison-04", "Madison Hotel", "423 E 7th St", 200, 200, "Healthy Housing Foundation"),
            ("rosslyn-05", "Rosslyn Hotel Annex", "451 S Main St", 264, 264, "SRO Housing Corp")
        ]
        cursor.executemany("""
            INSERT OR IGNORE INTO sro_hotels (id, name, street_address, total_historic_units, current_active_units, operator_nonprofit)
            VALUES (?, ?, ?, ?, ?, ?);
        """, sro_data)
        self.conn.commit()

    def register_demolition_and_replacement(self, OriginalHotelId, RedevelopmentProject, UnitsDemolished, ReplacementUnits, ReplacementSiteAddress):
        """
        Enforces the 1:1 Replacement Rule. If ReplacementUnits < UnitsDemolished, the transaction fails audit.
        """
        cursor = self.conn.cursor()
        
        # Fetch SRO Hotel
        cursor.execute("SELECT name, current_active_units FROM sro_hotels WHERE id = ?;", (OriginalHotelId,))
        hotel = cursor.fetchone()
        if not hotel:
            return {"status": "FAILED", "message": f"SRO Hotel with ID '{OriginalHotelId}' not found in registry."}

        # Check if 1:1 rule is violated mathematically
        rule_violation = ReplacementUnits < UnitsDemolished
        covenant_status = "Violated" if rule_violation else "Certified"
        
        cov_id = f"COV-{uuid_mock()}"
        
        try:
            # 1. Update SRO Active count
            new_active_count = max(0, hotel['current_active_units'] - UnitsDemolished)
            cursor.execute("UPDATE sro_hotels SET current_active_units = ? WHERE id = ?;", (new_active_count, OriginalHotelId))
            
            # 2. Insert Covenant Entry
            cursor.execute("""
                INSERT INTO replacement_covenants (id, redevelopment_project, original_hotel_id, units_demolished, replacement_units_covenanted, replacement_site_address, covenant_status)
                VALUES (?, ?, ?, ?, ?, ?, ?);
            """, (cov_id, RedevelopmentProject, OriginalHotelId, UnitsDemolished, ReplacementUnits, ReplacementSiteAddress, covenant_status))
            
            self.conn.commit()
            
            if rule_violation:
                return {
                    "status": "VIOLATION",
                    "covenant_id": cov_id,
                    "message": f"CRITICAL: 1:1 replacement rule violated for '{RedevelopmentProject}'! Demolished {UnitsDemolished} SRO units but only covenanted {ReplacementUnits} replacement units."
                }
            else:
                return {
                    "status": "APPROVED",
                    "covenant_id": cov_id,
                    "message": f"Certified: 1:1 replacement covenant validated for '{RedevelopmentProject}'. {UnitsDemolished} SRO units replaced."
                }
        except Exception as e:
            self.conn.rollback()
            return {"status": "FAILED", "message": f"Transaction rolled back: {e}"}

    def fetch_audit_summary(self):
        cursor = self.conn.cursor()
        cursor.execute("""
            SELECT c.id as covenant, c.redevelopment_project, h.name as original_hotel,
                   c.units_demolished, c.replacement_units_covenanted, c.covenant_status
            FROM replacement_covenants c
            JOIN sro_hotels h ON c.original_hotel_id = h.id;
        """)
        return [dict(row) for row in cursor.fetchall()]

# Helper function to generate safe unique identifiers
_uuid_counter = 1000
def uuid_mock():
    global _uuid_counter
    _uuid_counter += 1
    return str(_uuid_counter)


# ==============================================================================
# TRACK C: PROSOCIAL CIVIC TRUST PORTAL (NLP SoM MITIGATOR)
# ==============================================================================
class ProsocialCivicTrustPortal:
    """
    Mitigates the 'Sense of Misinformation' (SoM) by detecting highly-polarized,
    unsubstantiated claims, providing local public policy facts, and offering
    prosocial paraphrasing alternatives to support community-wide dialogue.
    """
    SOM_TRIGGERS = [
        (r"\b(bribed|corruption|crooks?|shady|bribery)\b", 
         "DTLA 2040 was marked by high transparency inside the Planning Commission, though amendments require careful statutory verification. Let's focus on auditing specific planning requests rather than declaring bad intent."),
        (r"\b(demolish everything|kick out everyone|gentrifying our entire community)\b", 
         "The Downtown Community Plan (DTLA 2040) actually doubles the area where permanent supportive and affordable housing is permitted (expanding from 33% to 60%). Let's map coordinates to ensure individual SROs are protected under the 1:1 replacement ordinance.")
    ]

    @classmethod
    def evaluate_and_paraphrase(cls, user_text):
        """
        Analyzes post text, detects SoM risks, and constructs positive alternatives.
        """
        som_detected = False
        warnings = []
        factual_groundings = []

        for pattern, response in cls.SOM_TRIGGERS:
            if re.search(pattern, user_text, re.IGNORECASE):
                som_detected = True
                warnings.append(f"Polarizing language detected targeting: '{re.search(pattern, user_text, re.IGNORECASE).group(0)}'")
                factual_groundings.append(response)

        if not som_detected:
            return {
                "som_detected": False,
                "moderated_text": user_text,
                "factual_groundings": [],
                "warnings": []
            }

        # Dynamic prosocial re-write engine
        moderated_text = user_text
        # Clean up hostile/unsubstantiated claims with constructive demand framing
        moderated_text = re.sub(r"\b(bribed|crooks?|corruption)\b", "unregulated administrative variances", moderated_text, flags=re.IGNORECASE)
        moderated_text = re.sub(r"\b(kick out everyone|demolish everything)\b", "reduce our historical affordable SRO housing stock", moderated_text, flags=re.IGNORECASE)
        
        # Append policy demand
        moderated_text += "\n\nProposed Action: We urge the City Council to fully expand the IX1 (Affordable Housing Only) zone across all historical Skid Row boundaries to ensure covenanted protections."

        return {
            "som_detected": True,
            "original_text": user_text,
            "moderated_text": moderated_text,
            "factual_groundings": factual_groundings,
            "warnings": warnings
        }


# ==============================================================================
# INTEGRATED ENGINE TEST RUNNER & SIMULATOR
# ==============================================================================
def run_integrated_fccw_simulation():
    print(TerminalColors.HEADER + TerminalColors.BOLD + "="*80)
    print("FOURTH & CENTRAL COMMUNITY WATCHDOG (FCCW) - MONITORING & COGNITIVE SHIELD RUNNER")
    print("="*80 + TerminalColors.ENDC)

    # 1. Test Track A: Zoning Audit GIS Simulation
    print(TerminalColors.OKCYAN + "\n[TRACK A: GIS Zoning Audit Simulation]" + TerminalColors.ENDC)
    
    # Proposal 1: Fourth & Central Project (Replacing a cold storage facility on perimeter)
    # Total units: 1600, Affordable: 250 (~15%). Location: At boundary edge
    fcc_audit = ZoningAuditEngine.audit_development_proposal(
        project_name="Fourth & Central Megabuild",
        lat=34.0458,
        lon=-118.2390,
        proposed_units=1600,
        affordable_units=250,
        zoning_requested="IX2"
    )
    print(f"Project: {fcc_audit['project']}")
    print(f"Status: {fcc_audit['zoning_compliance']}")
    print(f"Affordability Level: {fcc_audit['affordability_rate']}%")
    for warn in fcc_audit["warnings"]:
        print(TerminalColors.WARNING + f"  ⚠️  {warn}" + TerminalColors.ENDC)

    # Proposal 2: Luxury loft proposing IX1 rezoning inside historical boundary
    luxury_incursion = ZoningAuditEngine.audit_development_proposal(
        project_name="Winston Street Luxury Lofts",
        lat=34.0442,
        lon=-118.2438,
        proposed_units=200,
        affordable_units=10,
        zoning_requested="IX1"
    )
    print(f"\nProject: {luxury_incursion['project']}")
    print(f"Status: {TerminalColors.FAIL if luxury_incursion['severity'] == 'CRITICAL' else TerminalColors.WARNING}{luxury_incursion['zoning_compliance']}{TerminalColors.ENDC}")
    for warn in luxury_incursion["warnings"]:
        print(TerminalColors.FAIL + f"  🚫  {warn}" + TerminalColors.ENDC)


    # 2. Test Track B: SRO 1:1 Replacement Ledger Database Audit
    print(TerminalColors.OKCYAN + "\n[TRACK B: SRO 1:1 Replacement Ledger Audit]" + TerminalColors.ENDC)
    ledger = SROLedgerEngine()
    ledger.seed_initial_sro_data()

    # Log an Approved Replacement Covenants
    rep_certified = ledger.register_demolition_and_replacement(
        OriginalHotelId="renato-01",
        RedevelopmentProject="Renato Phase II Upgrade",
        UnitsDemolished=40,
        ReplacementUnits=40,
        ReplacementSiteAddress="538 S San Julian St (On-site rebuilt)"
    )
    print(f"Transaction 1: {rep_certified['message']}")

    # Log a Violated Replacement Covenant (Loss of units)
    rep_violated = ledger.register_demolition_and_replacement(
        OriginalHotelId="king-edward-03",
        RedevelopmentProject="King Edward Luxury conversion",
        UnitsDemolished=80,
        ReplacementUnits=12,
        ReplacementSiteAddress="318 W 9th St (Off-site deficit)"
    )
    print(TerminalColors.FAIL + f"Transaction 2: {rep_violated['message']}" + TerminalColors.ENDC)


    # 3. Test Track C: Prosocial Civic Trust Portal (SoM Mitigator)
    print(TerminalColors.OKCYAN + "\n[TRACK C: Prosocial Civic Trust Portal (Countering SoM)]" + TerminalColors.ENDC)
    
    angry_post = "The city council and developers are crooks! They were bribed to demolish everything in Skid Row and kick out everyone to build luxury lofts for wealthy tech transplants!"
    print(f"\nUser Post Draft:\n\"{angry_post}\"")
    
    som_mitigation = ProsocialCivicTrustPortal.evaluate_and_paraphrase(angry_post)
    if som_mitigation["som_detected"]:
        print(TerminalColors.WARNING + "\n⚠️  Sense of Misinformation (SoM) Risk Detected! Modifying with Factual Policy Context..." + TerminalColors.ENDC)
        print("\nFactual Grounding Reference provided to User:")
        for fact in som_mitigation["factual_groundings"]:
            print(TerminalColors.OKGREEN + f"  ✓ {fact}" + TerminalColors.ENDC)
            
        print("\nSuggested Prosocial / Constructive Paraphrase:")
        print(TerminalColors.BOLD + som_mitigation["moderated_text"] + TerminalColors.ENDC)

    print("\n" + TerminalColors.HEADER + "="*80)
    print("Simulations complete. All modules operational.")
    print("="*80 + TerminalColors.ENDC)

if __name__ == "__main__":
    run_integrated_fccw_simulation()
