#!/usr/bin/env python3
"""
FOURTH & CENTRAL COMMUNITY WATCH (FCCW) & SAFEHAVEN DEVELOPMENT SUITE
Master Simulation Orchestrator
Author: Generated by Gemini Notebook for FCCW & SafeHaven Initiatives
License: Open Source (GPL-3.0)
Year: 2026

This orchestrator consolidates all local backend, database, zoning API, and 
unit test simulations developed across this workspace. It is designed to run 
seamlessly on both macOS and Android Termux environments.
"""

import os
import sys
import subprocess
import time
from datetime import datetime

# =============================================================================
# COLORFUL TERMINAL CONFIGURATION
# =============================================================================
class TerminalColors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

# =============================================================================
# HELPER RUNNER FUNCTIONS
# =============================================================================
def run_command(command_list, description, expected_exit_code=0):
    print(f"\n{TerminalColors.OKCYAN}🚀 Running: {description}...{TerminalColors.ENDC}")
    print(f"Executing: {' '.join(command_list)}")
    print(TerminalColors.HEADER + "-"*60 + TerminalColors.ENDC)
    
    start_time = time.time()
    try:
        # Run process and pipe output directly to stdout/stderr
        result = subprocess.run(command_list, check=False)
        elapsed_time = time.time() - start_time
        
        if result.returncode == expected_exit_code:
            print(TerminalColors.HEADER + "-"*60 + TerminalColors.ENDC)
            print(f"{TerminalColors.OKGREEN}✓ Success! Completed in {elapsed_time:.3f}s.{TerminalColors.ENDC}")
            return True
        else:
            print(TerminalColors.HEADER + "-"*60 + TerminalColors.ENDC)
            print(f"{TerminalColors.FAIL}❌ Failed! Process exited with code {result.returncode} in {elapsed_time:.3f}s.{TerminalColors.ENDC}")
            return False
            
    except Exception as e:
        print(TerminalColors.HEADER + "-"*60 + TerminalColors.ENDC)
        print(f"{TerminalColors.FAIL}❌ Exception occurred: {e}{TerminalColors.ENDC}")
        return False

# =============================================================================
# MAIN ORCHESTRATION SEQUENCER
# =============================================================================
def main():
    print(TerminalColors.HEADER + TerminalColors.BOLD + "="*80)
    print("           SAFEHAVEN & FCCW INTEGRATED WORKSPACE SIMULATION SUITE")
    print("="*80 + TerminalColors.ENDC)
    print(f"System: {sys.platform} | Time: {datetime_now()}")
    print("Starting master test sequence and pipeline verification...")
    
    # Track results
    stages = []
    
    # -------------------------------------------------------------------------
    # STAGE 1: Unit Test Suite
    # -------------------------------------------------------------------------
    test_script = "tests/test_watchdog.py"
    if os.path.exists(test_script):
        res = run_command(
            [sys.executable, "-m", "unittest", test_script],
            "Stage 1: Executing Watchdog Unit Test Suite"
        )
        stages.append(("Unit Test Suite", res))
    else:
        test_script_fallback = "test_watchdog.py"
        if os.path.exists(test_script_fallback):
            res = run_command(
                [sys.executable, "-m", "unittest", test_script_fallback],
                "Stage 1: Executing Watchdog Unit Test Suite (Subfolder)"
            )
            stages.append(("Unit Test Suite", res))
        else:
            print(f"{TerminalColors.WARNING}⚠️  test_watchdog.py not found. Skipping Stage 1.{TerminalColors.ENDC}")
            stages.append(("Unit Test Suite", None))

    # -------------------------------------------------------------------------
    # STAGE 2: SafeHaven Database Setup and Seed Data
    # -------------------------------------------------------------------------
    seed_script = "database/seed.py"
    if os.path.exists(seed_script):
        res = run_command(
            [sys.executable, seed_script],
            "Stage 2: Initializing Relational DDL & Seeding SafeHaven Database"
        )
        stages.append(("Database Setup & Seeding", res))
    else:
        seed_script_fallback = "database/seed.py"
        if os.path.exists(seed_script_fallback):
            res = run_command(
                [sys.executable, seed_script_fallback],
                "Stage 2: Initializing Relational DDL & Seeding SafeHaven Database (Subfolder)"
            )
            stages.append(("Database Setup & Seeding", res))
        else:
            print(f"{TerminalColors.WARNING}⚠️  database/seed.py not found. Skipping Stage 2.{TerminalColors.ENDC}")
            stages.append(("Database Setup & Seeding", None))

    # -------------------------------------------------------------------------
    # STAGE 3: SafeHaven Intake & Bed Booking Simulation
    # -------------------------------------------------------------------------
    intake_script = "database/simulate_intake.py"
    if os.path.exists(intake_script):
        res = run_command(
            [sys.executable, intake_script],
            "Stage 3: Running Low-Barrier Intake Transaction Simulation"
        )
        stages.append(("Intake & Bed Booking", res))
    else:
        intake_script_fallback = "database/simulate_intake.py"
        if os.path.exists(intake_script_fallback):
            res = run_command(
                [sys.executable, intake_script_fallback],
                "Stage 3: Running Low-Barrier Intake Transaction Simulation (Subfolder)"
            )
            stages.append(("Intake & Bed Booking", res))
        else:
            print(f"{TerminalColors.WARNING}⚠️  database/simulate_intake.py not found. Skipping Stage 3.{TerminalColors.ENDC}")
            stages.append(("Intake & Bed Booking", None))

    # -------------------------------------------------------------------------
    # STAGE 4: Real-Time Services Dashboard Query
    # -------------------------------------------------------------------------
    query_script = "database/query_services.py"
    if os.path.exists(query_script):
        res = run_command(
            [sys.executable, query_script],
            "Stage 4: Querying Real-Time Care Coordination Dashboard Logs"
        )
        stages.append(("Dashboard Queries", res))
    else:
        query_script_fallback = "database/query_services.py"
        if os.path.exists(query_script_fallback):
            res = run_command(
                [sys.executable, query_script_fallback],
                "Stage 4: Querying Real-Time Care Coordination Dashboard Logs (Subfolder)"
            )
            stages.append(("Dashboard Queries", res))
        else:
            print(f"{TerminalColors.WARNING}⚠️  database/query_services.py not found. Skipping Stage 4.{TerminalColors.ENDC}")
            stages.append(("Dashboard Queries", None))

    # -------------------------------------------------------------------------
    # STAGE 5: FCCW Multi-Track Watchdog Runner
    # -------------------------------------------------------------------------
    fccw_script = "fccw_watchdog.py"
    if os.path.exists(fccw_script):
        res = run_command(
            [sys.executable, fccw_script],
            "Stage 5: Running FCCW Watchdog Multi-Track Simulation Engine"
        )
        stages.append(("FCCW Watchdog Engine", res))
    else:
        fccw_script_fallback = "fccw-watchdog/fccw_watchdog.py"
        if os.path.exists(fccw_script_fallback):
            res = run_command(
                [sys.executable, fccw_script_fallback],
                "Stage 5: Running FCCW Watchdog Multi-Track Simulation Engine (Subfolder)"
            )
            stages.append(("FCCW Watchdog Engine", res))
        else:
            print(f"{TerminalColors.WARNING}⚠️  fccw_watchdog.py not found. Skipping Stage 5.{TerminalColors.ENDC}")
            stages.append(("FCCW Watchdog Engine", None))

    # -------------------------------------------------------------------------
    # STAGE 6: FCCW Real-Time API Monitor (MIME & Twilio Alerts)
    # -------------------------------------------------------------------------
    api_script = "fccw_api_monitor.py"
    if os.path.exists(api_script):
        res = run_command(
            [sys.executable, api_script],
            "Stage 6: Running FCCW GIS Open Data API Monitor & Alert Dispatch"
        )
        stages.append(("GIS API Monitor & Alerts", res))
    else:
        api_script_fallback = "fccw-watchdog/fccw_api_monitor.py"
        if os.path.exists(api_script_fallback):
            res = run_command(
                [sys.executable, api_script_fallback],
                "Stage 6: Running FCCW GIS Open Data API Monitor & Alert Dispatch (Subfolder)"
            )
            stages.append(("GIS API Monitor & Alerts", res))
        else:
            # Let's try v2 or original if v3 is not found
            fallback_options = [
                "fccw_api_monitor-v2.py",
                "fccw_api_monitor.py",
                "fccw-watchdog/fccw_api_monitor-v2.py",
                "fccw-watchdog/fccw_api_monitor.py",
            ]
            found_fallback = False
            for opt in fallback_options:
                if os.path.exists(opt):
                    res = run_command(
                        [sys.executable, opt],
                        f"Stage 6: Running FCCW GIS Open Data API Monitor (Fallback: {opt})"
                    )
                    stages.append(("GIS API Monitor & Alerts", res))
                    found_fallback = True
                    break
            if not found_fallback:
                print(f"{TerminalColors.WARNING}⚠️  No FCCW API monitor found. Skipping Stage 6.{TerminalColors.ENDC}")
                stages.append(("GIS API Monitor & Alerts", None))

    # -------------------------------------------------------------------------
    # STAGE 7: Spatial Data Map Compiler
    # -------------------------------------------------------------------------
    map_script = "fccw_spatial_map.py"
    if os.path.exists(map_script):
        res = run_command(
            [sys.executable, map_script],
            "Stage 7: Compiling GIS Spatial Map & Visualizing Contested Boundaries"
        )
        stages.append(("GIS Map Compiler", res))
    else:
        map_script_fallback = "fccw-watchdog/fccw_spatial_map.py"
        if os.path.exists(map_script_fallback):
            res = run_command(
                [sys.executable, map_script_fallback],
                "Stage 7: Compiling GIS Spatial Map & Visualizing Contested Boundaries (Subfolder)"
            )
            stages.append(("GIS Map Compiler", res))
        else:
            print(f"{TerminalColors.WARNING}⚠️  fccw_spatial_map.py not found. Skipping Stage 7.{TerminalColors.ENDC}")
            stages.append(("GIS Map Compiler", None))

    # =============================================================================
    # MASTER SUMMARY REPORT
    # =============================================================================
    print("\n" + TerminalColors.HEADER + "="*80)
    print("                    MASTER WORKSPACE INTEGRATION SUMMARY")
    print("="*80 + TerminalColors.ENDC)
    
    all_passed = True
    any_executed = False
    
    for name, result in stages:
        if result is True:
            print(f"  🟢 {TerminalColors.OKGREEN}PASS{TerminalColors.ENDC}       | {name:<35}")
            any_executed = True
        elif result is False:
            print(f"  🔴 {TerminalColors.FAIL}FAIL{TerminalColors.ENDC}       | {name:<35}")
            all_passed = False
            any_executed = True
        else:
            print(f"  🟡 {TerminalColors.WARNING}SKIPPED{TerminalColors.ENDC}    | {name:<35}")
            
    print(TerminalColors.HEADER + "="*80 + TerminalColors.ENDC)
    
    if not any_executed:
        print(f"{TerminalColors.WARNING}⚠️  No simulation scripts were executed. Ensure files are extracted to your current working directory.{TerminalColors.ENDC}")
    elif all_passed:
        print(f"{TerminalColors.OKGREEN}{TerminalColors.BOLD}🎉 Available SafeHaven & FCCW stages completed successfully!{TerminalColors.ENDC}")
    else:
        print(f"{TerminalColors.FAIL}{TerminalColors.BOLD}🚨 PIPELINE ALERT: One or more stages failed during master execution. Check details above.{TerminalColors.ENDC}")
    print(TerminalColors.HEADER + "="*80 + TerminalColors.ENDC)

def datetime_now():
    try:
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    except Exception:
        return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())

if __name__ == "__main__":
    main()
